---
- name: download spc jar file
  hosts: all
  become: yes
  tasks:
    - name: install spc
      get_url:
        url: https://devbucket9.s3.eu-west-3.amazonaws.com/spring-petclinic-3.0.0-SNAPSHOT.jar
        dest: /home/ubuntu
    - name: copy the service file
      copy:
        src: spc.service
        dest: /etc/systemd/system/spc.service
        mode: "777"
    - name: daemon reload
      systemd:
        name: spc.service
        daemon_reload: yes
        state: started
        enabled: yes